# This file makes it easy for anyone to immediately launch this repo in a new gitpod.io workspace
# See https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml
# See also: ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

# previously:
#  - init: yarn install && yarn run build

tasks:
    - init: yarn install
      command: yarn run dev

ports:
    - port: 3000
      onOpen: open-preview
      description: Website preview

github:
    prebuilds:
        # enable for the default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # add a check to pull requests (defaults to true)
        addCheck: prevent-merge-on-error
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false
        # add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: true
